config/routes.rb
LOCALCYCLE::Application.routes.draw do

  resources :categories

  resources :products do
    get 'pic', on: :member
    get 'export', on: :collection
  end

  resources :price_points

  resources :goods do
    get 'toggle_available', on: :member
    get 'marketplace', on: :collection
    get 'export', on: :collection
    get 'buyer_panel', on: :collection
    get 'buyer_panel', on: :member

  end

  resources :markets do
    get 'export', on: :collection
  end
  resources :networks do
    get 'export', on: :collection
  end
  
  resources :agreements do
    get 'root_agreement_changes', on: :member
    put 'accept', on: :member
    get 'marketplace', on: :collection
    get 'table', on: :collection
    get 'export', on: :collection
    resources :agreement_changes, only: ["new","create","update"] do
      post 'chain', on: :collection
    end
  end

  devise_for :users, path_prefix: "d", path_names: { sign_in: 'login', sign_up: 'register' },
    controllers: {confirmations: 'confirmations', sessions: 'sessions', registrations: 'registrations'}

  devise_scope :user do
    put '/users/confirm' => 'confirmations#confirm', as: :user_confirm
    get '/login', :to => "devise/sessions#new"
    get '/register', :to => "registrations#new"
  end

  resources :users do
    get 'prompt', on: :member
    get 'export', on: :collection
    member do 
      post 'activate'
      post 'approve_network'
      post 'remove_network'
      
    end
  end

  resources :wishlists
  
  resources :orders
  resources :sub_orders
  
  
  resources :carts do
    member do
      post 'add_item' 
      get 'checkout'
      post 'clear'
      post 'remove_item'
    end
    
  end
  
  # Temporary model to collect email addresses on BETA page
  resources :leads, only: "create"

  # Reserved for admin to test different user views
  match 'become' => "users#become"

  root :to => 'public#index'

  # Public pages
  match "for-farmers" => 'public#for_farmers'
  match "for-buyers" => 'public#for_buyers'
  match "about-us" => 'public#about_us'
  match "contact" => 'public#contact'
  match "test" => 'public#test'
  match "d/users" => 'public#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :order
  
  has_many :cart_items, :dependent => :destroy
  
  attr_accessible :cart_items_attributes
  
  
  accepts_nested_attributes_for :cart_items
  
  def clear_cart
    
  end
  
  
  def total
     total =0.0
		cart_items.includes(:good).each do |item|
	    total = total + ((item.price+ (item.price*item.markup/100)) * item.quantity)
	  end
    total
  end
  
  def producer_total
     total =0.0
		cart_items.includes(:good).each do |item|
	    total = total + (item.price * item.quantity)
	  end
    total
  end
  
  
  def dist_fees
    fee =0
    cart_items.collect{|c| c.market}.uniq.each do |m|
      fee = fee + m.distribution_fee
    end
    fee
    
  end
  
  private 
  
  
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    load_resource :except => :checkout

include ActionView::Helpers::NumberHelper

def clear
  @cart.cart_items.each do |ci|
    CartItem.delete(ci.id)
  end
  
  render :partial => 'carts/show', :locals => {cart: @cart}
  
end

def update
  authorize! :update, @cart
  @cart.assign_attributes(params[:cart])
  
  @cart.cart_items.each do |item|
    
      price_point = Hash.new 
  		item.good.price_points.each do |pp|		
  			if JSON.parse(pp.buyers)["#{item.market.id.to_s}"] != nil
  				 if (JSON.parse(pp.buyers)["#{item.market.id.to_s}"].count == 0 )
  					 price_point["#{pp.quantity.to_s}"] = pp if price_point["#{pp.quantity.to_s}"] == nil
  				else
  						 if (JSON.parse(pp.buyers)["#{item.market.id.to_s}"].include? ("#{@cart.user.id.to_s}"))
  								 price_point["#{pp.quantity.to_s}"] = pp 
  						end
  				end			
  			end
  		end				
	
		  price_holder = nil
  		 price_point.keys.sort.each do |key|
  			 pp = price_point[key]
  			 if (item.quantity >= key.to_i)
  			   price_holder = pp.price 
  		   end
  		end
    
      if(price_holder == nil ) 
        flash[:error] = "Must have min order of #{price_point.keys.sort.first} for #{item.good.name}"
        redirect_to :back
        return
      end
    
      if(!Good.find(item.good_id).no_qty && Good.find(item.good_id).quantity.to_i < item.quantity)
          flash[:error] =  "Not enough quantity available for #{item.good.name}"
          redirect_to :back
         return
      end
  end
  
  if @cart.update_attributes(params[:cart])
    flash[:notice] = "cart updated"
  else
    flash[:error] =" There was an issue updating your cart"
  end
  
  render :checkout
end

def add_item
   authorize! :update, @cart
   cart_item = @cart.cart_items.where(:good_id => params[:good_id], :market_id => params[:market_id]).first
   
   calc_use = 0
   @cart.cart_items.where(:good_id => params[:good_id]).each do |v|
    calc_use = calc_use + v.quantity
   end
   
   if cart_item.nil? 
     raise "Must be min order" if(params[:qty].to_i < params[:min_order].to_i) 
     if(!Good.find(params[:good_id]).no_qty && Good.find(params[:good_id]).quantity.to_i < params[:qty].to_i)
       render :text => "Not enough quantity available"
        return
     end
     CartItem.create(:good_id => params[:good_id], :quantity => params[:qty], :market_id => params[:market_id], :cart_id => @cart.id, :markup=> (Market.find(params[:market_id]).markup == nil ? 0 : Market.find(params[:market_id]).markup))
   else     
     if(!Good.find(params[:good_id]).no_qty && Good.find(params[:good_id]).quantity.to_i < calc_use + params[:qty].to_i)
       render :text => "Not enough quantity available"
        return
     end
     cart_item.quantity = cart_item.quantity + params[:qty].to_i
     cart_item.save
   end
   render :partial => 'carts/show', :locals => {cart: @cart}

end

def remove_item
  CartItem.delete(params[:cart_item_id])
  render :nothing => true
  
end


def checkout

  begin
  @cart = Cart.find(params[:id])
  items = current_user.get_cart.cart_items.sort! { |a,b| a.market.name.downcase <=> b.market.name.downcase }
	items.collect{|ci| ci.market}.uniq.each do |market|
	  
	  market_total = 0.0
		@cart.cart_items.where(:market_id => market.id).each do |item|
			 market_total = market_total + ((item.price+ (item.price*item.markup/100)) * item.quantity)
		end
		market_total = market_total + market.distribution_fee
		if market_total < (market.order_min == nil ? 0 : market.order_min)
	    flash[:error] = "#{market.name} minimum order is #{number_to_currency(market.order_min)}. Please add more to your cart to checkout." 
	    redirect_to :back
	  else
	    producer_hash = Hash.new
  	  items.each do |i|
  	    
  	    producer_hash[i.good.creator_id] = Hash.new if(!producer_hash.keys.include?(i.good.creator_id))
  	    producer_hash[i.good.creator_id][i.market_id] = 0 if(!producer_hash[i.good.creator_id].keys.include?(i.market_id))
        producer_hash[i.good.creator_id][i.market_id] = producer_hash[i.good.creator_id][i.market_id] + (i.price+ (i.price*i.markup/100)) * i.quantity
      end
      producer_hash.keys.each do |key|
        producer_hash[key].keys.each do |market|
          if producer_hash[key][market] < ( User.find(key).minimum_orders.where(:market_id=>market).first ? User.find(key).minimum_orders.where(:market_id=>market).first.min_order : 0)+ (( User.find(key).minimum_orders.where(:market_id=>market).first ? User.find(key).minimum_orders.where(:market_id=>market).first.min_order : 0)*Market.find(market).markup/100)
            flash[:error] = "#{User.find(key).name} requires a minimum order of #{number_to_currency(( User.find(key).minimum_orders.where(:market_id=>market).first ? User.find(key).minimum_orders.where(:market_id=>market).first.min_order : 0)+ (( User.find(key).minimum_orders.where(:market_id=>market).first ? User.find(key).minimum_orders.where(:market_id=>market).first.min_order : 0)*Market.find(market).markup/100) )} for #{Market.find(market).name}." 
      	    redirect_to :back

          end
          
        end
      end
	  end
	end
	
    
  if @cart.order == nil
    @cart.build_order(:user_id => current_user.id) 
    @cart.save
  end
  rescue
    flash[:error] ="Could not process transaction. You have no items in your cart."
    redirect_to marketplace_goods_path
    return
  
  end
  
end

end

app/views/carts/_show.html.haml
.cart_body
	.row-fluid
		.span9.offset2
			%h4.center
				- total =0.0
				="Your Order"
	.row-fluid
		.span12
			-items = current_user.get_cart.cart_items.sort! { |a,b| a.market.name.downcase <=> b.market.name.downcase }
			-items.collect{|ci| ci.market}.uniq.each do |market|
				- sub_total = 0.0
				%h5.center
					= market.name if market
				%br
				-current_user.get_cart.cart_items.where(:market_id => market.id).collect{|g| g.good.creator}.uniq.each do |farm|
					="#{farm.name}"
					.underline
					- current_user.get_cart.cart_items.includes(:good).where(:market_id => market.id).where('goods.creator_id = ?', farm.id).each do |item|
						.row-fluid
							.span6
								= item.good.name
							.span6.price
								= " #{number_to_currency(item.price+ (item.price*item.markup/100))} x #{item.quantity}" 
								- sub_total = sub_total + ((item.price + (item.price*item.markup/100) )* item.quantity)
				%hr
				.row-fluid
					.span6
						="Distribution Fee:"
					.span6.price
						= "#{number_to_currency(market.distribution_fee)}"
						-sub_total = sub_total +(market.distribution_fee == nil ? 0 : market.distribution_fee )
				.row-fluid
					.span6
						="Subtotal:"
					.span6.price
						= "#{number_to_currency(sub_total)}"
						- total = total + sub_total
				%br
					
			.underline
			.row-fluid
				.span6
					="Total:"
				.span6.price
					= "#{number_to_currency(total)}"
		
	

					
					
					

	.row-fluid
		.span9.offset2
			-if (current_user.get_cart.cart_items.count != 0)
				= link_to "Checkout", checkout_cart_path(current_user.get_cart),class: "btn btn-warning checkout-btn"
				= link_to "Clear Cart", clear_cart_path(current_user.get_cart), class: "btn btn-warning add-to-cart"
			  
		

app/views/carts/checkout.html.haml
=form_for @cart do |f|
	- total =0.0

	.row
		.span12
			%h1
				=image_tag "/assets/icon-mrkt.png", :alt=>"Calendar Icon", :class=>'big-icon'
				Your Order
			
	.row
		.span2.offset6
			Quantity
		.span2.price
			Price
		.span2.price
			Subtotal
	%hr

	.row
		.span12
			-items = current_user.get_cart.cart_items.sort! { |a,b| a.market.name.downcase <=> b.market.name.downcase }
			-items.collect{|ci| ci.market}.uniq.each do |market|
				%h3
					= market.name if market
				%h5
					=market.billing_street_address_1
					=market.billing_street_address_2
					=", #{market.billing_city} #{market.billing_state}, #{market.billing_zip}"
					%br
				

				%br
				-current_user.get_cart.cart_items.where(:market_id => market.id).collect{|g| g.good.creator}.uniq.each do |farm|
					- sub_total = 0.0
				
					%h4
						="#{farm.name}"
					%h5
						="#{farm.first_name} #{farm.last_name}"

					.underline
					- current_user.get_cart.cart_items.includes(:good).where(:market_id => market.id).where('goods.creator_id = ?', farm.id).each do |item|
						=f.fields_for :cart_items, item do |g|
							.row-fluid
								
								.span6
									-url = "/carts/#{@cart.id}/remove_item" 
									%i.icon-trash.remove_cart_item{:data=>{:url=> "#{url}", :item=>"#{item.id}"}}
									= "#{item.good.name} (#{SellingUnit.find(item.good.selling_unit_id).name})"
								.span2
									= g.text_field :quantity, :style=>"width: 40px"
								.span2.price
									= " #{number_to_currency(item.price+ (item.price*item.markup/100))}" 
								.span2.price
									="#{number_to_currency((item.price+ (item.price*item.markup/100)) * item.quantity)}"
									- sub_total = sub_total + ((item.price+ (item.price*item.markup/100)) * item.quantity)
					%hr
					.row-fluid
						.span12.price
							= "#{number_to_currency(sub_total)}"
							- total = total + sub_total
					%br

			.underline
			.row-fluid
				.span2.offset9
					%h5
						%br
						="Distribution Fee:"
				.span1.price
					%h5
						%br
						= "#{number_to_currency(current_user.get_cart.dist_fees)}"
			.row-fluid
				.span2.offset9
					%h5
						%br
						="Order Total:"
				.span1.price
					%h5
						%br
						= "#{number_to_currency(total +current_user.get_cart.dist_fees)}"

			.row-fluid
				.span9
					=link_to "Print Your Order", '#', :class=> "print_page"
					%br
					=link_to "Continue Shopping", goods_path
				.span3.price
					%br
						-if (current_user.get_cart.cart_items.count == 0)
							.btn.btn-warning.disabled
								Add Items to Cart to Checkout
						-else
							.row-fluid
								.span4
									= f.submit "Update Cart", :class=>"btn btn-warning ", :style=>"display:inline;"
								.span8
									= link_to "<div class='btn btn-warning checkout-btn'>Proceed To Checkout</div>".html_safe, edit_order_path(@cart.order)
				
		