config/routes.rb
LOCALCYCLE::Application.routes.draw do

  resources :categories

  resources :products do
    get 'pic', on: :member
    get 'export', on: :collection
  end

  resources :price_points

  resources :goods do
    get 'toggle_available', on: :member
    get 'marketplace', on: :collection
    get 'export', on: :collection
    get 'buyer_panel', on: :collection
    get 'buyer_panel', on: :member

  end

  resources :markets do
    get 'export', on: :collection
  end
  resources :networks do
    get 'export', on: :collection
  end
  
  resources :agreements do
    get 'root_agreement_changes', on: :member
    put 'accept', on: :member
    get 'marketplace', on: :collection
    get 'table', on: :collection
    get 'export', on: :collection
    resources :agreement_changes, only: ["new","create","update"] do
      post 'chain', on: :collection
    end
  end

  devise_for :users, path_prefix: "d", path_names: { sign_in: 'login', sign_up: 'register' },
    controllers: {confirmations: 'confirmations', sessions: 'sessions', registrations: 'registrations'}

  devise_scope :user do
    put '/users/confirm' => 'confirmations#confirm', as: :user_confirm
    get '/login', :to => "devise/sessions#new"
    get '/register', :to => "registrations#new"
  end

  resources :users do
    get 'prompt', on: :member
    get 'export', on: :collection
    member do 
      post 'activate'
      post 'approve_network'
      post 'remove_network'
      
    end
  end

  resources :wishlists
  
  resources :orders
  resources :sub_orders
  
  
  resources :carts do
    member do
      post 'add_item' 
      get 'checkout'
      post 'clear'
      post 'remove_item'
    end
    
  end
  
  # Temporary model to collect email addresses on BETA page
  resources :leads, only: "create"

  # Reserved for admin to test different user views
  match 'become' => "users#become"

  root :to => 'public#index'

  # Public pages
  match "for-farmers" => 'public#for_farmers'
  match "for-buyers" => 'public#for_buyers'
  match "about-us" => 'public#about_us'
  match "contact" => 'public#contact'
  match "test" => 'public#test'
  match "d/users" => 'public#index'

end

app/models/good.rb
class Good < ActiveRecord::Base

  ############# CONFIGURATION #############

  ## SETUP ASSOCIATIONS
  belongs_to :product
  belongs_to :selling_unit
  belongs_to :buyer, class_name: "User", foreign_key: :buyer_id
  belongs_to :producer, class_name: "User", foreign_key: :producer_id
  belongs_to :creator, class_name: "User", foreign_key: :creator_id
  
  belongs_to :wishlist
  has_and_belongs_to_many :certifications
  has_many :price_points, dependent: :destroy
  accepts_nested_attributes_for :price_points, allow_destroy: true, reject_if: proc { |attrs| attrs['price'].blank? or attrs['quantity'].blank? or attrs['selling_unit_id'].blank? }

  has_and_belongs_to_many :markets

  has_attached_file :pic, styles: IMAGE_STYLES, default_url: DEFAULT_PAPERCLIP_IMAGE

  ## ATTRIBUTE PROTECTION  
  
  attr_accessible :product_id, :quantity, :start_date, :end_date, :creator_id, :market_id, :price_points_attributes, :available, :selling_unit_id, :certification_ids, :wishlist_id, :producer_id, :cycle, :description, :order_cutoff, :pic, :no_qty


  ## ATTRIBUTE VALIDATION

  validates :product_id, :creator_id, presence: true

  validates :available,
    :inclusion => {:in => [true, false]}

  validate :must_have_price_point

  #validates :end_date, presence: true
  #########################################




  ############### CALLBACKS ###############

  #before_validation
  #after_validation
  #before_save
  #before_create
  #after_create
  #after_save
  #after_commit

  #########################################



  ################ SCOPES #################

  scope :in_month, lambda{|m| {:conditions => ['end_date >= ? AND start_date <= ?', Date.new(Date.today.year, m.to_i, 1), Date.new(Date.today.year, m.to_i, 1).end_of_month]}}

  
  scope :available_supply, where(buyer_id: 0)
  scope :available_demand, where(producer_id: 0)

  scope :by_name, lambda { |n| includes(:product).where('UPPER(products.name) LIKE UPPER(?)', '%'+n+'%')}
#  scope :by_min_price, lambda {|p| where("price >= ?", p.to_i)}
#  scope :by_max_price, lambda {|p| where("price <= ?", p.to_i)}
  scope :by_min_quantity, lambda {|q| where("quantity >= ?", q.to_i)}
  scope :by_max_quantity, lambda {|q| where("quantity <= ?", q.to_i)}
  scope :by_buyer, lambda {|b| where("buyer_id = ?", b)}
  scope :by_producer, lambda {|p| where("producer_id = ?", p)}
  scope :by_creator, lambda {|p| where("creator_id = ?", p)}
  scope :by_product, lambda {|p| where("product_id = ?", p)}
  scope :by_market, lambda {|n| joins(:markets).("market.id = ?", n)}
  scope :in_category, lambda { |c| includes(:product).where("products.category_id IN (?)", Category.where(id: c).first.self_and_descendant_ids) }

  #########################################



  ############ CLASS METHODS ##############


  
  def update_markets
    self.markets.each do |m|
      self.markets.delete(m)
    end
    price_points.each do |pp|
      puts "#{pp.buyers.to_yaml}"
      hash = JSON.parse pp.buyers
      hash.each do |market|
          mark = Market.find(market[0].to_i)
          self.markets << mark if !self.markets.include?(mark) 
      end
      
    end
    
  end
  
  
  #def self.
  def self.csv_header 
    "ID,Name,Description,Season Start Date,Season End Date".split(',') 
  end

  def self.build_from_csv(row)
    good = Good.where(id: row[0]).first_or_initialize
    start_date = row[6].split("-")
    end_date = row[7].split("-")
    good.attributes = {
      :unit_type => row[4],
      :catch_weight => row[5],
      :start_date => Date.new(start_date[2].to_i, start_date[0].to_i, start_date[1].to_i),
      :end_date => Date.new(end_date[2].to_i, end_date[0].to_i, end_date[1].to_i),
    }
    return good
  end


  ############ PUBLIC METHODS #############

  def must_have_price_point
    if price_points.empty? or price_points.all? {|pp| pp.marked_for_destruction? }
      errors.add(:base, 'Must have at least one price point')
    end
  end

  def to_csv
    [id, name, description, start_date, end_date]
  end

  def quantity
    read_attribute(:quantity).nil? ? "--" : read_attribute(:quantity)
  end

  def name
    product.name
  end

  def users
    users = []
    users << buyer if buyer
    users << producer if producer
    return users
  end
  def user_names
    users.map {|u| u.name }.join(' + ')
  end

  def created_by?(u)
    creator_id == u.id
  end
  def has_producer?
    producer_id != 0
  end
  def has_buyer?
    buyer_id != 0
  end

  def duration
    "Expires " + end_date.strftime("%b %e") if end_date
  end

  def has_certification(c_id)
    ids = certifications.collect{|cert| cert.id}
    return ids.include(c_id)
  end
  
  def best_pic_url(sym)
    (pic?) ? pic.url(sym) : product.best_pic_url(sym)
  end

  ############ PRIVATE METHODS ############
  private

end

app/controllers/goods_controller.rb
require 'uri'

class GoodsController < ApplicationController
  load_and_authorize_resource

  helper_method :sort_column, :sort_direction
  
  require 'csv'

  def marketplace
    # Ensure profile has been created
    redirect_to edit_user_path(current_user) and return unless current_user.complete

    @goods = Good.scoped.includes(:product, :price_points).where(:wishlist_id => nil)
    @cat_id =  params.has_key?(:cat_id) ? params[:cat_id] : nil

    #toggle off good
    @goods.where("goods.start_date > ? or goods.end_date < ?", Date.current,Date.current).each do |g|
      g.available = false
      g.save
    end
    
    if current_user.buyer? && current_user.networks.length >0
        @network = Network.find( params.has_key?(:network_id) ? params[:network_id] : current_user.networks.first.id )
        @market = params.has_key?(:market_id) ? Market.find(params[:market_id]) : current_user.markets.where(:network_id => @network.id).first
        @goods = @goods.where("goods.start_date <= ?", Date.current).where("goods.end_date is null or goods.end_date >= ?", Date.current).where(:available => true)
    end
    @goods = filter_and_sort(@goods, params)
    @goods = @goods.paginate(page: params[:page], per_page: (params[:per_page] || DEFAULT_PER_PAGE))

    @product_goods = @goods.group_by(&:product)

    respond_to do |format|
      format.html { render (current_user.role == 'buyer' ? 'buyer_marketplace' : 'marketplace')}      
      format.json { render json: @goods }
    end
  end

  def index
    # Ensure profile has been created
    redirect_to edit_user_path(current_user) and return unless current_user.complete

    
    @good = Good.new()
    @good.price_points.build()

    @cat_id =  params.has_key?(:cat_id) ? params[:cat_id] : nil
    @goods = Good.scoped.includes(:product, :price_points).where(:wishlist_id => nil)
    
    @goods = @goods.by_creator(current_user) if current_user.producer?

    #toggle off good
    @goods.where("goods.start_date > ? or goods.end_date < ?", Date.current,Date.current).each do |g|
      g.available = false
      g.save
    end

    if current_user.buyer? 
        @network = Network.find( params.has_key?(:network_id) ? params[:network_id] : current_user.networks.first.id )
        @market = params.has_key?(:market_id) ? Market.find(params[:market_id]) : current_user.markets.where(:network_id => @network.id).first
        @goods = @goods.where("goods.start_date <= ?", Date.current).where("goods.end_date is null or goods.end_date >= ?", Date.current).where(:available => true)
        
    end
    
    @goods = filter_and_sort(@goods, params)
    
    if current_user.market_manager?
      remove_goods = Array.new
      current_user.markets.each do |m|
        remove_goods = remove_goods + m.goods
      end
      remove_goods = remove_goods.map{|m| m.id}
      
      @goods = @goods.where(:id=>remove_goods)
    end
    
    @goods = @goods.paginate(page: params[:page], per_page: (params[:per_page] || DEFAULT_PER_PAGE))
    
    
    respond_to do |format|
      format.html { render (current_user.role == 'buyer' ? 'buyer_index' : 'index')}
         
      
      format.json { render json: @goods }
    end
  end

  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @good }
      format.js
    end
  end


  def pic

    respond_to do |format|
      format.js {}
    end
  end


  def new
    @good = Good.new()

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @good }
    end
  end

  def edit
    render :layout => false
  end


  def create
    
    respond_to do |format|
      if @good.save
        @good.update_markets if !current_user.buyer?
        @good.price_points.each do |p|
          if (p.producer_id != -1)
            ProducerMailer.new_demand(@good.id, current_user, p, p.producer_id).deliver if params[:good].has_key?(:wishlist_id) 
          else
            users = Array.new
            current_user.networks.each do |n|
              n.users.where(:role => 'producer').each do |pro|
                ProducerMailer.new_demand(@good.id, current_user, p, pro.id).deliver if params[:good].has_key?(:wishlist_id) && !users.include?(pro.id)
                users << pro.id
              end
            end
              
          end
          
        end
        
        
        format.html { redirect_to goods_url, notice: 'Good was successfully created.' }
        format.json { render json: @good, status: :created, location: @good }
        format.js { render (params[:good].has_key?(:wishlist_id) ? 'wishlists/create' : :create)}
      else
        format.html { render action: "new" }
        format.json { render json: @good.errors, status: :unprocessable_entity }
        format.js { render :create_error }
      end
    end
  end 


  def update
    respond_to do |format|
      if @good.update_attributes(params[:good])
        Good.find(@good.id).update_markets if !current_user.buyer?
        if !current_user.buyer? && (@good.order_cutoff == nil || @good.order_cutoff == '')
          @good.order_cutoff = @good.creator.default_cutoff
          @good.save
        end
        
        if params[:render] == 'false'
           render :nothing=> true
           return
        end
        format.html { redirect_to (current_user.buyer? ? wishlist_url(current_user.wishlist) : goods_url), notice: 'Good was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  def buyer_panel
    puts "IN BUYER PANEL"
    @target_id = params[:target]
    @data = URI.unescape(params[:data])
    render :layout=>false
  end

  def destroy
    wishlist_id = @good.wishlist_id
    @good.destroy

    respond_to do |format|
      format.html { redirect_to  (wishlist_id != nil ? wishlist_path(wishlist_id) : goods_url) }
      format.json { head :no_content }
    end
  end

  def toggle_available
    @good = Good.find(params[:id])

    @good.update_column("available", !@good.available)
    
    respond_to do |format|
      format.html { redirect_to goods_url, notice: "#{@good.name} is #{@good.available ? 'now' : 'no longer'} available" }
      format.json { render json: { id: @good.id, available: @good.available, message: "#{@good.name} is #{@good.available ? 'now' : 'no longer'} available" } }
    end
  end


  def export 
    goods = filter_and_sort(@goods, params)

    filename = "goods_#{Date.today.strftime('%b-%d-%y')}"
    csv_data = CSV.generate do |csv|
      csv << Good.csv_header
      goods.includes(:product).each do |t|
        csv << t.to_csv
      end
    end
    send_data csv_data,
      :type => 'text/csv; charset=iso-8859-1; header=present',
      :disposition => "attachment; filename=#{filename}.csv"
  end

  def import
    if request.post? && params[:file].present?
      errs = import_records(params[:file], "good")
    end
    # Export Error file for later upload upon correction 
    if errs.any? 
      errFile = "good_errors_#{Date.today.strftime('%b-%d-%y')}.csv"
      csv_errs = CSV.generate do |csv|
        csv << Good.csv_header + ",Error"
        errs.each {|row| csv << row}
      end 
      send_data csv_errs, 
      :type => 'text/csv; charset=iso-8859-1; header=present', 
      :disposition => "attachment; filename=#{errFile}"
    else
      redirect_to goods_path, notice: "Successfully imported goods" and return
    end
  end

  private

  def filter_and_sort(goods, params)
    @search = params[:search] if(params.has_key?(:search))
    @filters = params[:filter] if(params.has_key?(:filter))
    
    #goods = goods.by_market(current_user.markets.first.id) unless current_user.admin?
    goods = goods.by_market(params[:market]) unless params[:market].blank?
    goods = goods.by_name(params[:name]) unless params[:name].blank?
    goods = goods.by_category(params[:category]) unless params[:category].blank?
    goods = goods.by_product(params[:product]) unless params[:product].blank?
    goods = goods.in_category(params[:cat_id]) unless params[:cat_id].blank?

    filtered_goods = Good.all
    
    if(params.has_key?(:filter))
      params[:filter].split(',').each do |f|
        all_certs = Certification.find(f).goods
        filtered_goods = filtered_goods & all_certs
      end
    end
    
    filtered_goods = filtered_goods.map{|m| m.id}
    
    if(params.has_key?(:search))
      if(params[:search] != '')
        goods = goods.includes(:product).includes(:creator).where("LOWER(products.name) like LOWER('%#{URI.unescape(params[:search])}%')")
      end
    end
    
    return goods.includes(:creator).where(:id=>filtered_goods).order(sort_column + " " + sort_direction)
  end
  
  
  def sort_column
    sort = params[:sort] || ''
    (sort !='' || sort == "selling_units.name") ? sort : "products.name"
  end

  def sort_direction
    direction = params[:direction] || ''
    "ASC DESC".include?(direction) ? direction : "ASC"
  end
end

app/helpers/goods_helper.rb
module GoodsHelper
  def parsed_params
    new_params = {}
    new_params[:name]=params[:name] unless params[:name].blank?
    new_params[:price]=params[:price] unless params[:price].blank?
    new_params[:producer]=params[:producer] unless params[:producer].blank?
    new_params[:availability]=params[:availability] unless params[:availability].blank?

    new_params[:per_page]=params[:per_page] unless params[:per_page].blank?
    new_params
  end

  def full_params
    new_params = {}
    new_params[:name]=params[:name] unless params[:name].blank?
    new_params[:price]=params[:price] unless params[:price].blank?
    new_params[:producer]=params[:producer] unless params[:producer].blank?
    new_params[:availability]=params[:availability] unless params[:availability].blank?

    new_params[:sort]=params[:sort] unless params[:sort].blank?
    new_params[:direction]=params[:direction] unless params[:direction].blank?

    new_params[:per_page]=params[:per_page] unless params[:per_page].blank?
    new_params
  end
end

app/views/goods/_buyer_sorters.html.erb
<tr class="sorters">
  <th style="width: 160px;"><%= sortable "farm", "Farm", parsed_params %></th>
  <th><%= sortable "product", "Product", parsed_params %></th>

  <th><%= sortable "quantity", "Qty Avail", parsed_params %></th>
  <th><%=  "Price Points" %></th>
  <th><span>Actions</span></th>
</tr>

app/views/goods/_good.html.erb
<%= content_tag_for :tr, good, class: (current_user.buyer? ? (good.available ? "success" : "error") : "") do %>

<%= form_for(good, html: { multipart: true, class: "form-horizontal" }) do |f| %>


<td>
	<% if current_user.market_manager? or current_user.admin? or good.created_by?(current_user) %>
	   <%= link_to toggle_available_good_path(good), class: 'ajax-available', data: { type: 'json' }, remote: true do %><span title="Click to toggle availability of <%= good.name %>" class="label label-<%= good.available ? 'success' : 'important' %>"><i class="icon-ok icon-white"></i></span><% end %>
	 <% end %>
</td>
  <td class='name <%= (params[:sort] == "name") ? "sorted" : "" %>'>
    <%= image_tag good.best_pic_url(:thumb), class: "thumb" %>
    <%= link_to good.product.name, good, data: {target: "#ajax-modal", toggle: "modal", placement: "top", data: "true", remote: "true"} %>
  </td>
  <% if current_user.admin? or current_user.market_manager? %>
  <td class='producer <%= (params[:sort] == "producer.name") ? "sorted" : "" %>'>
    <%= image_tag good.creator.pic(:thumb), class: "thumb" %>
    <%= link_to good.creator.name, good.creator, data: {target: "#ajax-modal", toggle: "modal", placement: "top", data: "true", remote: "true"} %>
  </td>
  <% end %>



  <td>
    <%= f.fields_for :price_points do |fpp| %>
      <%= render partial: 'price_points/form', locals: { f: fpp, good: good } %>
      <%= new_child_fields_template(f, :price_points, {partial: "price_points/batch_form"})%>
    <% end %>
    <span class="controls">

      <span class="help-inline"><%= add_child_link "Price Point", :price_points %></span>
			</div>
  </td>

  <td>
		<span class="controls controls-row">
      <%= f.number_field :quantity, placeholder: "Qty", class: "span2", style: "width: 30px" , :min => 0, :readonly=> f.object.no_qty %>
      <%= f.select :selling_unit_id, SellingUnit.all.map {|s| [s.short_name, s.id]}, {prompt: "Unit"}, {class: "span1", style: "width: 75px; margin-left: 5px;"} %>
		</div><br/>
		<%= f.check_box :no_qty%><div style="font-size: 10px; line-height:10px; margin-top: -10px; margin-left: 13px">Unknown/Unlimited Qty</div>

  </td>



 
  <td>
    <div class="btn-toolbar">
      <div class="btn-group">
	<% if good.created_by?(current_user) or current_user.admin? or current_user.market_manager? %>
          <%= link_to raw('<i class="icon-edit"></i> Details'), edit_good_path(good), title: "Edit good info", remote: true, class: "btn btn-small good-details-btn" %>
          <%= link_to raw('<i class="icon-trash"></i> Delete'), good_path(good, full_params.to_hash), data: {confirm: "Are you sure you want to permanently delete this good and all its information?"}, title: "Delete this good from the system", method: :delete, class: "btn btn-small" %>
					<br/>
					<div class="btn btn-primary save_line" style="display: none" data-url ="<%= good_path(good) %>">Save</div>
	<% else %>
	  <%= link_to "Add to Cart", "#", class: "btn btn-warning" %>
	<% end %>
      </div>
    </div>
  </td>

	<% end %>
	<% end %>

app/views/goods/_marketplace_good.html.erb
<div class="product base_container">
  <%= image_tag good.best_pic_url(:medium), class: "medium" %>
  <%= hidden_field_tag :good_id, good.id%>
	
  <h4><%= link_to good.product.name, good, data: {target: "#ajax-modal", toggle: "modal", placement: "top", data: "true", remote: "true"} %></h4>
  <h5><a href="/users/<%= good.creator.id%>" data-remote="true"><%= good.creator.name %></a><br/>
	<%= "min. order for producer: #{number_to_currency(good.creator.minimum_orders.where(:market_id=>@market.id).first ? good.creator.minimum_orders.where(:market_id=>@market.id).first.min_order : 0)}"%></h5>
  <div class="certs underline">
		<div class="row-fluid">
			<div class="span9">
				<% good.certifications.each do |c|%>
						<%= c.name%><br/>
					<%end%><br/>
				
			</div>
			<div class="span3">
				<%= number_field :cart_item, :quantity, placeholder: "Qty",  style: "width: 50px", min: 0, max: good.quantity %>

				<%= good.selling_unit.name%>(s)<br/>
			  
			</div>
		</div>
		<br/>
	</div>
	
  <p class="details">
		<% price_point = Hash.new %>
		<% if @market != nil%>
			<% good.price_points.each do |pp|%>		
				<% if pp.buyers && JSON.parse(pp.buyers)["#{@market.id.to_s}"] != nil%>
					<% if (JSON.parse(pp.buyers)["#{@market.id.to_s}"].count == 0 )%>
						<% price_point["#{pp.quantity.to_s}"] = pp if price_point["#{pp.quantity.to_s}"] == nil%>
					<%else%>
							<% if (JSON.parse(pp.buyers)["#{@market.id.to_s}"].include? ("#{current_user.id.to_s}"))%>
									<% price_point["#{pp.quantity.to_s}"] = pp %>
							<%end%>
					<%end%>			
				<%end%>
			<%end%>				
		<%end%>
		<%= price_point.keys.count == 0 ? "No Price Point For This Market" : ""%>
		<%= hidden_field_tag :min_order, price_point.keys.sort.first%>
		<% price_point.keys.sort.each do |key|%>
			<% pp = price_point[key]%>
			<%markup = @market.markup==nil ? 0 : @market.markup%>
			<%= number_to_currency(pp.price + (pp.price*markup/100)) %>/<%= good.selling_unit.name%> for min order of <%= pp.quantity %> <%= good.selling_unit.name%><%= good.quantity.to_i > 1 ? "s" : ''%> <br/>
			
		<%end%>


  </p>

  <p class="centered">
    <% if good.created_by?(current_user) %>
      <div class="btn-group">
	<%= link_to raw('<span class="icon-edit"></span> Edit Listing'), edit_good_path(good), class: "btn-small btn" %>
	<%= link_to raw('<span class="icon-trash"></span> Delete'), good_path(good, full_params.to_hash), data: {confirm: "Are you sure you want to permanently delete this good and all its information?"}, title: "Delete this good from the system", method: :delete, class: "btn btn-small" %>
      </div>
    <% else %>
    <%= good.no_qty ? "unlimited" : good.quantity %> <span class="label label-info"><%= good.selling_unit.short_name.pluralize %></span> avail.<br />
		<%= hidden_field_tag :available, good.quantity %>
		<br/>
		  <%= link_to "Add to Cart", add_item_cart_path(current_user.get_cart), class: "btn btn-warning add-to-cart", :disabled => ( price_point.keys.count == 0 ) %>
			

    <% end %>
  </p>
</div>

app/views/goods/_query_form.html.erb
<tr class="input-row">
	<% span = current_user.producer? ? 4 : 5%>
  <td colspan=<%= span %>></td>
    <td>
      <div id="buttons">
	<div class="btn-group">
		<%= link_to " <div class='btn btn-inverse'><i class='icon-list-alt icon-white'></i> Export...</div>".html_safe, export_goods_path(params), id: "export_csv" %>
	 
      </div>
    </td>
</tr>

app/views/goods/_sorters.html.erb
<tr class="sorters">
  <th>Available <br/>This Week?</th>
  <th style="width: 160px;"><%= sortable "products.name", "Product", parsed_params %></th>
  <% if current_user.admin? or current_user.market_manager? %>
  <th style="width: 160px;"><%= sortable "users.name", "Producer", parsed_params %></th>
  <% end %>
  <th><%=  "'Price by Min. Amount"%></th>
  <th><%= sortable "quantity", "Qty Avail", parsed_params %></th>
  <th><span>Actions</span></th>
</tr>

app/views/goods/buyer_index.html.erb
<%= render "partials/ajax-modal" %>

<div class="row">
  <div class="span12">
    <div class="btn-group pull-right actions-bar">
      <%= link_to raw('<span class="icon-th-large icon-white"></span> Product View'), marketplace_goods_path, class: "btn btn-primary" %>
      <%#= link_to 'New Good', new_good_path, class: "btn btn-primary" %>
      <%= link_to raw('<span class="icon-question-sign"></span>'), "#", class: "btn" %>
    </div>
    <h1><a href="<%= goods_path%>"><img class="big-icon" src="/assets/icon-agreements-calendar.png" alt="Calendar Icon" /> Goods</a></h1>
		<div <%= " style=visibility:hidden;height:0px !important;" if current_user.networks.count == 1  %> >
			Showing supply for: <%= select :network, :id, current_user.networks.collect{|n| [n.name, n.id]}, :class=> "buyer_network_select"%>
		</div>
  </div>
</div>


<div class="row">
  <div class="span9 to_replace">
		<div class="row-fluid">
			<div class="span5">
				Available Distribution Points: <%= select :market, :id, current_user.markets.where(:network_id => @network.id).collect{|n| [n.name, n.id]}, :class=> "buyer_market_select"%>
			</div>
			<div class="span7">
				 <%if @market%>
				<%date= @market.next_market%>
				<% date = "TBD" if date == nil%>
				
					<h3> <%=@market.name%> - <%= date == "TBD" ? "TDB" : date.to_formatted_s(:long)%></h3>
					<h5> <%=@market.address%></h5><br/>
				<%end%>
			</div>
		</div>
    	<div id="error-div"></div>
    	<%= render "cert_filters" %>

    	<%= render "partials/filters" %>

			<% if date !=nil && @market.start_orders != nil && Time.current < date-@market.start_orders.hours || Time.current > date-(@market.end_orders == nil ? 0 : @market.end_orders.hours) %>
				<h5><%= "Orders are not currently being taken for this market." %><br/><%="This market will open again for orders from <b>#{(date-@market.start_orders.hours).to_formatted_s(:long)} to #{(date-(@market.end_orders == nil ? 0 : @market.end_orders.hours)).to_formatted_s(:long)}</b>".html_safe%></h5>
			<%else%>
    	<table id="good-table" class="table table-hover table-striped">

  	    <thead id="sorters">
					<%= render "buyer_sorters" %>
	      </thead>
		    
	      <tbody id="good-ajax">
	        <% if @goods.any? %>
	          <% @goods.each do |good| %>
								<% gh =  good.order_cutoff ? good.order_cutoff  : 0%>
								<% next if @market && @market.start_time  && DateTime.current > @market.next_market - gh.to_i.hours %>
		    				<%= render partial: "buyer_good", locals: {good: good, network_id: @network.id} %>
	          <% end %>

	        <% else %>
	          <tr><td colspan="<%= (current_user.admin? or current_user.market_manager?) ? '7' : '6' %>"><em>No matching Goods...</em> </td></tr>
	        <% end %>
	      </tbody>
	    </table>


    <div id="pagination">
      <%= will_paginate @goods %>
    </div>
<%end%>

  </div>
	<div class="span3">
		<%= render :partial => 'carts/show' %>
	</div>
</div>

app/views/goods/new.html.erb
<h1>New Good</h1>

<%= render 'form' %>