config/routes.rb
LOCALCYCLE::Application.routes.draw do

  resources :categories

  resources :products do
    get 'pic', on: :member
    get 'export', on: :collection
  end

  resources :price_points

  resources :goods do
    get 'toggle_available', on: :member
    get 'marketplace', on: :collection
    get 'export', on: :collection
    get 'buyer_panel', on: :collection
    get 'buyer_panel', on: :member

  end

  resources :markets do
    get 'export', on: :collection
  end
  resources :networks do
    get 'export', on: :collection
  end
  
  resources :agreements do
    get 'root_agreement_changes', on: :member
    put 'accept', on: :member
    get 'marketplace', on: :collection
    get 'table', on: :collection
    get 'export', on: :collection
    resources :agreement_changes, only: ["new","create","update"] do
      post 'chain', on: :collection
    end
  end

  devise_for :users, path_prefix: "d", path_names: { sign_in: 'login', sign_up: 'register' },
    controllers: {confirmations: 'confirmations', sessions: 'sessions', registrations: 'registrations'}

  devise_scope :user do
    put '/users/confirm' => 'confirmations#confirm', as: :user_confirm
    get '/login', :to => "devise/sessions#new"
    get '/register', :to => "registrations#new"
  end

  resources :users do
    get 'prompt', on: :member
    get 'export', on: :collection
    member do 
      post 'activate'
      post 'approve_network'
      post 'remove_network'
      
    end
  end

  resources :wishlists
  
  resources :orders
  resources :sub_orders
  
  
  resources :carts do
    member do
      post 'add_item' 
      get 'checkout'
      post 'clear'
      post 'remove_item'
    end
    
  end
  
  # Temporary model to collect email addresses on BETA page
  resources :leads, only: "create"

  # Reserved for admin to test different user views
  match 'become' => "users#become"

  root :to => 'public#index'

  # Public pages
  match "for-farmers" => 'public#for_farmers'
  match "for-buyers" => 'public#for_buyers'
  match "about-us" => 'public#about_us'
  match "contact" => 'public#contact'
  match "test" => 'public#test'
  match "d/users" => 'public#index'

end

app/models/sub_order.rb
class SubOrder < ActiveRecord::Base
  attr_accessible  :order_id, :key, :market_id, :producer_id, :dist_cost, :total, :market_date, :delivery_window_day, :delivery_window_start, :delivery_window_end, :producer_total
  belongs_to :order
  belongs_to :market
  belongs_to :user, :foreign_key => 'producer_id'
  has_many :cart_items


  def producer
    User.find(producer_id)
  end

end

app/controllers/sub_orders_controller.rb
class SubOrdersController < ApplicationController
load_and_authorize_resource
helper_method :sort_column, :sort_direction

def index
    
  if current_user.producer?
    @sub_orders = SubOrder.where(:producer_id => current_user.id)
  elsif current_user.admin?
    @orders = Order.where('orders.id > -1')
    @sub_orders = SubOrder.where('sub_orders.id > -1')
  elsif current_user.market_manager?
    @sub_orders = SubOrder.where("market_id in (#{current_user.market_ids.map(&:inspect).join(', ')})")
    @orders = Order.where("id in (#{@sub_orders.collect{|c| c.order.id}.map(&:inspect).join(', ')})")

  
  end
  @sub_orders = filter_and_sort(@sub_orders, params)

end

def show
end

private

def filter_and_sort(orders, params)
  
  return orders.includes(:order).order(sort_column + " " + sort_direction)
end

def sort_column
  sort = params[:sort] || ''
  (sort !='' || sort == "orders.user_id") ? sort : "created_at"
end

def sort_direction
  direction = params[:direction] || ''
  "ASC DESC".include?(direction) ? direction : "ASC"
end

end

app/helpers/sub_orders_helper.rb
module SubOrdersHelper
  def parsed_params
    new_params = {}
    new_params[:key]= "#{params[:order_id] }_#{('a'..'z').to_a[params[:key].to_i]}" unless params[:key].blank?
    new_params[:total]=params[:total] unless params[:total].blank?
    new_params[:created_at]=params[:created_at] unless params[:created_at].blank?
    new_params[:producer_id]= User.find(params[:producer_id]).full_name unless params[:producer_id].blank?

    new_params[:per_page]=params[:per_page] unless params[:per_page].blank?
    new_params
  end
end

app/views/sub_orders/_admin_summary.html.haml
%br
=link_to "Print This Page", '#', :class=> "print_page"

%br

-total=0
-dist_fees =0
-market = sub_order.market
%br
.row
	.span12{:style=> "border:1px solid black; padding-top: 5px; padding-bottom: 5px"}
		%b
			="Distribution Point: #{market.name}"
			%br
			="Distribution Point Date: #{sub_order.market_date.to_formatted_s(:long)}"
			%br
			="Delivery Window: "
			-if sub_order.delivery_window_day != -1
				="#{WEEKDAYS[sub_order.delivery_window_day] }  -   #{NORMAL_HOURS[sub_order.delivery_window_start]}  to  #{NORMAL_HOURS[sub_order.delivery_window_end]}"
			%br
			="Buyer: "
			="#{sub_order.user.full_name}"
		%hr
		%br
		.row
			.span12
				%h5
					%b
						= "Sub Order #{sub_order.order_id}_#{ ('a'..'z').to_a[sub_order.key] }".upcase
				-sub_total =0
				-markup_total =0

				-items = sub_order.cart_items.sort! { |a,b| a.market.name.downcase <=> b.market.name.downcase }
				-sub_order.cart_items.where(:market_id => market.id).collect{|g| g.good.creator}.uniq.each do |farm|
					.row-fluid			
						.span3
							="#{farm.name}"
						.span1
							= "Quantity" 
						.span2.price
							= "Producer Price" 
						.span2.price
							= "Item Price" 
						.span2.price
							="Total"
						.span2.price
							="Total Markup"
					.underline
					- sub_order.cart_items.includes(:good).where(:market_id => market.id).where('goods.creator_id = ?', farm.id).each do |item|
						-markup = item.markup == nil ? 0 : item.markup
						.row-fluid			
							.span3
								= "#{item.good.name} (#{SellingUnit.find(item.good.selling_unit_id).name})"
							.span1
								="#{ item.quantity}"
							.span2.price
								= " #{number_to_currency(item.price)}" 
							.span2.price
								= " #{number_to_currency((item.price+(item.price*markup/100))  )}" 
							.span2.price
								- if current_user.producer?
									="#{number_to_currency(item.price * item.quantity)}"
									- sub_total = sub_total + (item.price * quantity)
								-else
									="#{number_to_currency((item.price+(item.price*markup/100))* item.quantity  )}"
									- sub_total = sub_total + ((item.price+(item.price*markup/100))* item.quantity)
							.span2.price
								="#{number_to_currency(((item.price+(item.price*markup/100)) * item.quantity)-item.price*item.quantity)}"
								-markup_total = markup_total +(((item.price+(item.price*markup/100)) * item.quantity)-item.price*item.quantity)
						
									
								
		%hr
		.row
			.span12
				.row-fluid			
					.span4
						%b
							Subtotal
					.span2.price
					.span2.price
					.span2.price
						="#{number_to_currency(sub_total)}"
						-total = total + sub_total
					.span2.price
						="#{number_to_currency(markup_total)}"
				
%br
%br				
.row
	.span12{:style=> "border:1px solid black; padding-top: 5px; padding-bottom: 5px"}
		Subtotal: 
		= "#{number_to_currency(total)}"
		%br
		Total:
		= "#{number_to_currency(dist_fees + total)}"

app/views/sub_orders/_sorters.html.haml
%tr{class: "sorters"}
	%th
		=  sortable "key", "Order", parsed_params
	%th
		= sortable "created_at", "Order Date", parsed_params
	- if !current_user.producer?
		%th
			= sortable "producer_id", "Producer", parsed_params
	%th
		= sortable "orders.user_id", "Buyer", parsed_params
	%th
		= sortable "market.name", "Distribution Point", parsed_params
	%th
		= sortable "market_date", "Distribution Point Date", parsed_params
	-if current_user.admin? || current_user.market_manager?
		%th
			= sortable "producer_total", "Producer Total", parsed_params
		%th
			=  "Markup ($)"
	
	%th
		= sortable "total", "Total", parsed_params

app/views/sub_orders/_summary.html.haml
%br
=link_to "Print This Page", '#', :class=> "print_page"

%br

-total=0
-dist_fees =0
-market = sub_order.market
%br
.row
	.span12{:style=> "border:1px solid black; padding-top: 5px; padding-bottom: 5px"}
		%b
			="#{market.name}"
			%br
			="#{sub_order.market_date.to_formatted_s(:long)}"
			%br
			="Delivery Window: "
			-if sub_order.delivery_window_day != -1
				="#{WEEKDAYS[sub_order.delivery_window_day] }  -   #{NORMAL_HOURS[sub_order.delivery_window_start]}  to  #{NORMAL_HOURS[sub_order.delivery_window_end]}"
			%br
			-if current_user.buyer?
				="Producer:"
				="#{sub_order.producer.full_name}"
			-else
				="Buyer: "
				="#{sub_order.order.user.full_name}"
				
		%hr
		%br
		.row
			.span12
				%h5
					%b
						= "Sub Order #{sub_order.order_id}_#{ ('a'..'z').to_a[sub_order.key] }".upcase
				-sub_total =0
				-items = sub_order.cart_items.sort! { |a,b| a.market.name.downcase <=> b.market.name.downcase }
				-sub_order.cart_items.where(:market_id => market.id).collect{|g| g.good.creator}.uniq.each do |farm|
					.row-fluid			
						.span6
							="#{farm.name}"
						.span2
							= "Quantity" 
						.span2.price
							= "Item Price" 
						.span2.price
							="Total"
					.underline
					- sub_order.cart_items.includes(:good).where(:market_id => market.id).where('goods.creator_id = ?', farm.id).each do |item|
						-markup = item.markup == nil ? 0 : item.markup
						.row-fluid			
							.span6
								= "#{item.good.name} (#{SellingUnit.find(item.good.selling_unit_id).name})"
							.span2
								="#{ item.quantity}"
							.span2.price
								- if current_user.producer?
									= " #{number_to_currency(item.price)}" 
								-else
									= " #{number_to_currency((item.price+(item.price*markup/100))  )}" 
							.span2.price
								- if current_user.producer?
									="#{number_to_currency(item.price * item.quantity)}"
									- sub_total = sub_total + (item.price * item.quantity)
								-else
									="#{number_to_currency((item.price+(item.price*markup/100))* item.quantity  )}"
									- sub_total = sub_total + ((item.price+(item.price*markup/100))* item.quantity)
								
									
								
		%hr
		.row
			.span12
				.row-fluid			
					.span6
						%b
							Subtotal
					.span2.price
					.span2.price
					.span2.price
						="#{number_to_currency(sub_total)}"
						-total = total + sub_total
%br
%br				
.row
	.span12{:style=> "border:1px solid black; padding-top: 5px; padding-bottom: 5px"}
		Subtotal: 
		= "#{number_to_currency(total)}"
		%br
		Total:
		= "#{number_to_currency(dist_fees + total)}"

app/views/sub_orders/index.html.haml
= render "partials/ajax-modal" 
.row
	.span12
		%h1
			%a{href: "#{orders_path}"}
				%img{class: "big-icon", src: "/assets/icon-agreements-calendar.png", alt: "Calendar Icon"} 
				Orders
				
%table{id: "order-table", class: "table table-hover table-striped"}
	%thead{id: "sorters"}
		= render "sorters"
	%tbody
		-@sub_orders.each do |sub_order|	
			%tr
				%td
					=link_to "#{sub_order.order_id}__#{ ('a'..'z').to_a[sub_order.key] }".upcase, sub_order
				%td
					="#{sub_order.created_at.strftime('%B %e, %Y %l:%M:%p')}"
				- if !current_user.producer?
					%td
						-if sub_order.user !=nil
							="#{sub_order.user.full_name}"
				%td
					-if sub_order.order.user !=nil
						="#{sub_order.order.user.full_name}"
				%td
					="#{sub_order.market.name}"
				%td
					="#{sub_order.market_date.strftime('%B %e, %Y %l:%M:%p')  if sub_order.market_date} "
				-if current_user.admin? || current_user.market_manager?
					%td
						="#{number_to_currency(sub_order.producer_total)}"
					%td
						- pt = sub_order.producer_total == nil ? 0 : sub_order.producer_total
						- t = sub_order.total == nil ? 0 : sub_order.total
						="#{number_to_currency(t-pt)}"
				%td
					-if current_user.producer?
						="#{number_to_currency(sub_order.producer_total)}"
					-else
						="#{number_to_currency(sub_order.total)}"

app/views/sub_orders/show.html.haml
-if current_user.admin? || current_user.market_manager?
	= render :partial =>'admin_summary', :locals=>{:sub_order => @sub_order} 
-else
	= render :partial=>'summary', :locals =>{:sub_order => @sub_order} 